"""Add global_rank and category_rank to PodcastDailyMetric

Revision ID: 20250101000000
Revises: 
Create Date: 2025-01-01 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20250101000000'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('podcast_daily_metrics', sa.Column('global_rank', sa.Integer(), nullable=True))
    op.add_column('podcast_daily_metrics', sa.Column('category_rank', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_podcast_daily_metrics_global_rank'), 'podcast_daily_metrics', ['global_rank'], unique=False)
    op.create_index(op.f('ix_podcast_daily_metrics_category_rank'), 'podcast_daily_metrics', ['category_rank'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_podcast_daily_metrics_category_rank'), table_name='podcast_daily_metrics')
    op.drop_index(op.f('ix_podcast_daily_metrics_global_rank'), table_name='podcast_daily_metrics')
    op.drop_column('podcast_daily_metrics', 'category_rank')
    op.drop_column('podcast_daily_metrics', 'global_rank')
    # ### end Alembic commands ###


